language: php

php:
  - 7.1
  - 7.2
  - 7.3

install: composer install

script:
  - vendor/bin/phpstan analyse --no-interaction --no-progress
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage_clover.xml

after_script:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email:
    - sam@badcow.co